version: '3'

services:

  mongodb:
    container_name: mango_mongo
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./mongodb.env
    networks:
      - mango-network

  mongoseeder:
    container_name: mango_mongoseeder
    build:
      context: .
      dockerfile: mongo.seeder.dockerfile
    depends_on:
      - mongodb
    networks:
      - mango-network

networks:
  mango-network:
    driver: bridge
