name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  tests:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno: ["1.4.6"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Mango Unit Tests
        run: echo TODO # deno test -A ...

      - name: Mango Integration Tests
        run: echo TODO # deno test -A ...

      - name: BSON Unit Tests
        run: echo TODO # ...

  linter:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check

      - name: Linter
        run: deno lint
